# Generated by Django 4.0.2 on 2022-09-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('zł', 'Polska złotówka'), ('USD', 'Amerykański dolar'), ('EUR', 'Euro')], max_length=3),
        ),
    ]
