branch-defaults:
  main:
    environment: ictir-env
environment-defaults:
  ictir-env:
    branch: null
    repository: null
global:
  application_name: ictir
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
